apiVersion : apps/v1
kind: Deployment
metadata:
  name: song-service
  namespace: kubernetes-for-devs
  labels:
    app: song-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song-service
  template:
    metadata:
      labels:
        app: song-service
    spec:
      containers:
        - name : song-service
          image: markkazyrytski/song-service:v1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:postgresql://song-db:5432/postgres'
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgresPW
          ports:
            - containerPort: 8080
              name: song-service

---

apiVersion: v1
kind: Service
metadata:
  name: song-service
  namespace: kubernetes-for-devs
  labels:
    app: song-service
spec:
  type: ClusterIP
  selector:
    app: song-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080