apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kubernetes-for-devs
  name: song-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   namespace: kubernetes-for-devs
#   name: song-persistent-volume
# spec:
#   capacity:
#    storage: 1Gi
#   accessModes:
#    - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual
#   hostPath:
#     path: "/mnt/songs/data"

# ---