apiVersion : apps/v1
kind: Deployment
metadata:
  name: resource-service
  namespace: kubernetes-for-devs
  labels:
    app: resource-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource-service
  template:
    metadata:
      labels:
        app: resource-service
    spec:
      containers:
        - name : resource-service
          image: markkazyrytski/resource-service:v1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: resource-service-configmap
                  key: database-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: resource-service-secret
                  key: database-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resource-service-secret
                  key: database-password
            - name: SONGSERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: resource-service-configmap
                  key: song-service-host
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: resource-service
  namespace: kubernetes-for-devs
  labels:
    app: resource-service
spec:
  type: NodePort
  selector:
    app: resource-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080